//! Deterministic checked-in models.dev display-name and pricing generator.
//!
//! Normal builds never contact the network. Metadata refreshes are an explicit
//! maintainer operation whose reviewed output is committed under `models/`.

use std::collections::{BTreeMap, HashMap};
use std::env;
use std::fs;
use std::path::PathBuf;

const SNAPSHOT_PATH: &str = "models/models-dev-names.json";
const PRICING_SNAPSHOT_PATH: &str = "models/models-dev-pricing.json";

#[derive(Clone, Copy)]
struct PricingRecord {
    input: u64,
    output: u64,
    cache_read: u64,
    cache_write_5m: u64,
    reasoning: Option<u64>,
}

fn main() {
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={SNAPSHOT_PATH}");
    println!("cargo:rerun-if-changed={PRICING_SNAPSHOT_PATH}");

    let raw = fs::read_to_string(SNAPSHOT_PATH)
        .unwrap_or_else(|error| panic!("failed to read {SNAPSHOT_PATH}: {error}"));
    let names = parse_names(&raw)
        .unwrap_or_else(|error| panic!("invalid models.dev model metadata: {error}"));
    if names.is_empty() {
        panic!("models.dev model metadata contained no named models");
    }

    let pricing_raw = fs::read_to_string(PRICING_SNAPSHOT_PATH)
        .unwrap_or_else(|error| panic!("failed to read {PRICING_SNAPSHOT_PATH}: {error}"));
    let pricing = parse_pricing(&pricing_raw)
        .unwrap_or_else(|error| panic!("invalid models.dev pricing metadata: {error}"));
    if pricing.is_empty() {
        panic!("models.dev pricing metadata contained no priced models");
    }

    write_generated(&names);
    write_generated_pricing(&pricing);
}

fn parse_names(raw: &str) -> Result<BTreeMap<String, String>, serde_json::Error> {
    let root: serde_json::Value = serde_json::from_str(raw)?;
    let Some(models) = root.as_object() else {
        return Ok(BTreeMap::new());
    };
    let mut names = BTreeMap::new();
    for (key, model) in models {
        let id = model
            .get("id")
            .and_then(serde_json::Value::as_str)
            .unwrap_or(key)
            .trim();
        let name = model
            .get("name")
            .and_then(serde_json::Value::as_str)
            .or_else(|| model.as_str())
            .map(str::trim)
            .unwrap_or_default();
        if id.is_empty() || name.is_empty() || id.len() > 256 || name.len() > 256 {
            continue;
        }
        names.insert(id.to_ascii_lowercase(), name.to_owned());
    }
    Ok(names)
}

fn parse_pricing(raw: &str) -> Result<BTreeMap<String, PricingRecord>, String> {
    let root: serde_json::Value =
        serde_json::from_str(raw).map_err(|error| format!("invalid JSON: {error}"))?;
    let Some(models) = root.as_object() else {
        return Ok(BTreeMap::new());
    };
    let mut pricing = BTreeMap::new();
    for (key, model) in models {
        let Some(model) = model.as_object() else {
            continue;
        };
        let Some(input) = model.get("input").and_then(serde_json::Value::as_u64) else {
            continue;
        };
        let Some(output) = model.get("output").and_then(serde_json::Value::as_u64) else {
            continue;
        };
        if key.is_empty() || key.len() > 512 {
            continue;
        }
        let reasoning = match model.get("reasoning") {
            None | Some(serde_json::Value::Null) => None,
            Some(value) => Some(
                value
                    .as_u64()
                    .ok_or_else(|| format!("reasoning rate for {key:?} is not an integer"))?,
            ),
        };
        pricing.insert(
            key.to_ascii_lowercase(),
            PricingRecord {
                input,
                output,
                cache_read: model
                    .get("cache_read")
                    .and_then(serde_json::Value::as_u64)
                    .unwrap_or(0),
                cache_write_5m: model
                    .get("cache_write_5m")
                    .and_then(serde_json::Value::as_u64)
                    .unwrap_or(0),
                reasoning,
            },
        );
    }
    Ok(pricing)
}

fn write_generated(names: &BTreeMap<String, String>) {
    let mut leaf_counts: HashMap<&str, usize> = HashMap::new();
    for id in names.keys() {
        *leaf_counts
            .entry(id.rsplit('/').next().unwrap_or(id))
            .or_default() += 1;
    }
    let mut aliases = BTreeMap::new();
    for (id, name) in names {
        let leaf = id.rsplit('/').next().unwrap_or(id);
        if leaf_counts.get(leaf) == Some(&1) {
            aliases.insert(leaf, name);
        }
    }

    let mut generated = String::from(
        "// @generated by crates/ygg-ai/build.rs from the checked-in models.dev snapshot\n\
         pub(crate) static MODEL_NAMES: &[(&str, &str)] = &[\n",
    );
    for (id, name) in names {
        generated.push_str("    (");
        generated.push_str(&serde_json::to_string(id).expect("string serialization"));
        generated.push_str(", ");
        generated.push_str(&serde_json::to_string(name).expect("string serialization"));
        generated.push_str("),\n");
    }
    generated.push_str("];\npub(crate) static MODEL_NAME_ALIASES: &[(&str, &str)] = &[\n");
    for (id, name) in aliases {
        generated.push_str("    (");
        generated.push_str(&serde_json::to_string(id).expect("string serialization"));
        generated.push_str(", ");
        generated.push_str(&serde_json::to_string(name).expect("string serialization"));
        generated.push_str("),\n");
    }
    generated.push_str("];\n");

    let output =
        PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set")).join("models_dev_names.rs");
    fs::write(output, generated).expect("write generated models.dev names");
}

fn write_generated_pricing(pricing: &BTreeMap<String, PricingRecord>) {
    let mut generated = String::from(
        "// @generated by crates/ygg-ai/build.rs from the checked-in models.dev pricing snapshot\n\
         #[allow(clippy::type_complexity)]
pub(crate) static MODEL_PRICING: &[(&str, u64, u64, u64, u64, Option<u64>)] = &[\n",
    );
    for (id, rates) in pricing {
        generated.push_str("    (");
        generated.push_str(&serde_json::to_string(id).expect("string serialization"));
        generated.push_str(", ");
        generated.push_str(&rates.input.to_string());
        generated.push_str(", ");
        generated.push_str(&rates.output.to_string());
        generated.push_str(", ");
        generated.push_str(&rates.cache_read.to_string());
        generated.push_str(", ");
        generated.push_str(&rates.cache_write_5m.to_string());
        generated.push_str(", ");
        match rates.reasoning {
            Some(rate) => generated.push_str(&format!("Some({rate})")),
            None => generated.push_str("None"),
        }
        generated.push_str("),\n");
    }
    generated.push_str("];\n");

    let output = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR is set"))
        .join("models_dev_pricing.rs");
    fs::write(output, generated).expect("write generated models.dev pricing");
}
