// @generated by scripts/generate-extension-api-v03.py; DO NOT EDIT.
// Source: protocol/extension-api-v0.3.schema.json (sha256: 008bbdd83490c9bddb32fa4a903c053e36d7525653d8f63136a0de17d34890c1)
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };
export type JsonRpcId = string | number;
export type Presence<T> = { kind: 'absent' } | { kind: 'null' } | { kind: 'value'; value: T };
export type DispositionKind = 'continue' | 'deny' | 'defer';

export declare const API_VERSION: string;
export declare const SCHEMA_ID: string;
export declare const CANONICAL_ENCODING: string;
export declare const SCHEMA_SHA256: string;
export declare const MAX_PORTABLE_JSON_INTEGER: number;
export declare const MAX_FRAME_BYTES: number;
export declare const MAX_CONCURRENT_REQUESTS: number;
export declare const MAX_TOOLS: number;
export declare const MAX_CAPABILITIES: number;
export declare const MAX_METHODS: number;
export declare const MAX_CAPABILITY_NAME_BYTES: number;
export declare const MAX_METHOD_NAME_BYTES: number;
export declare const MAX_REASON_BYTES: number;
export declare const MAX_JSON_DEPTH: number;
export declare const MAX_CONTENT_PARTS: number;
export declare const MAX_TOOL_NAME_BYTES: number;
export declare const MAX_TOOL_DESCRIPTION_BYTES: number;
export declare const MAX_JSON_RPC_ID_BYTES: number;
export declare const API_VERSIONS: readonly Record<string, unknown>[];
export declare const LEGACY_ADAPTERS: readonly { version: string; status: string; wire: string }[];
export declare const CAPABILITY_SPECS: readonly Record<string, unknown>[];
export declare const METHOD_SPECS: readonly Record<string, unknown>[];
export declare const ERROR_SPECS: Readonly<Record<string, { code: number; message: string }>>;
export declare class ContractError extends Error { readonly code: number; readonly name: string; }
export declare function absent<T = never>(): Presence<T>;
export declare function nullPresence<T = never>(): Presence<T>;
export declare function present<T>(value: T): Presence<T>;

export interface ProtocolLimits {
  max_frame_bytes: number;
  max_concurrent_requests: number;
  max_tools: number;
}

export interface ContractOffer {
  schema: string;
  encoding: string;
  required_capabilities: string[];
  optional_capabilities: string[];
  required_methods: string[];
  optional_methods: string[];
  limits: ProtocolLimits;
}

export interface ContractSelection {
  schema: string;
  encoding: string;
  capabilities: string[];
  methods: string[];
  limits: ProtocolLimits;
}

export interface ToolDefinition {
  name: string;
  description: string;
  parameters: JsonValue;
  output_schema?: JsonValue;
}

export interface ToolCallParams {
  name: string;
  arguments: JsonValue;
  context: JsonValue;
}

export interface ToolCallResult {
  content: ContentPart[];
  is_error: boolean;
  metadata: JsonValue | null;
  structured_content?: Presence<JsonValue>;
}

export interface CancelRequestParams {
  id: JsonRpcId;
  reason?: string;
}

export interface CancelRequestResult {
  terminal: string;
  reason?: string;
}

export interface ShutdownParams {
}

export interface ShutdownResult {
  terminal: string;
}

export interface InitializeRequest {
  api_version: string;
  ygg_version: string;
  extension: JsonValue;
  workspace: string;
  capabilities: JsonValue;
  contributes: JsonValue;
  host: JsonValue;
  contract: ContractOffer;
}

export interface InitializeResponse {
  api_version: string;
  tools: ToolDefinition[];
  contract: ContractSelection;
}

export interface ErrorObject {
  code: number;
  message: string;
  data?: Presence<JsonValue>;
}

export interface Disposition {
  kind: DispositionKind;
  reason?: string;
}

export interface JsonRpcRequest {
  jsonrpc: string;
  id: JsonRpcId;
  method: string;
  params: JsonValue;
}

export interface JsonRpcNotification {
  jsonrpc: string;
  method: string;
  params: JsonValue;
}

export interface JsonRpcSuccessResponse {
  jsonrpc: string;
  id: JsonRpcId;
  result: JsonValue;
}

export interface JsonRpcErrorResponse {
  jsonrpc: string;
  id: JsonRpcId;
  error: ErrorObject;
}

export interface ContentPartText {
  type: "text";
  text: string;
}

export interface ContentPartImage {
  type: "image";
  artifact_id: string;
  mime_type: string;
  alt?: string;
}

export interface ContentPartAudio {
  type: "audio";
  artifact_id: string;
  mime_type: string;
  transcript?: string;
}

export type ContentPart = ContentPartText | ContentPartImage | ContentPartAudio;

export interface NegotiatedContract { capabilities: ReadonlySet<string>; methods: ReadonlySet<string>; limits: ProtocolLimits; }
export type JsonRpcEnvelope = JsonRpcRequest | JsonRpcNotification | JsonRpcSuccessResponse | JsonRpcErrorResponse;

export declare function parseProtocolLimits(value: unknown): ProtocolLimits;
export declare function parseContractOffer(value: unknown): ContractOffer;
export declare function parseContractSelection(value: unknown): ContractSelection;
export declare function parseToolDefinition(value: unknown): ToolDefinition;
export declare function parseToolCallParams(value: unknown): ToolCallParams;
export declare function parseToolCallResult(value: unknown): ToolCallResult;
export declare function parseCancelRequestParams(value: unknown): CancelRequestParams;
export declare function parseCancelRequestResult(value: unknown): CancelRequestResult;
export declare function parseShutdownParams(value: unknown): ShutdownParams;
export declare function parseShutdownResult(value: unknown): ShutdownResult;
export declare function parseInitializeRequest(value: unknown): InitializeRequest;
export declare function parseInitializeResponse(value: unknown): InitializeResponse;
export declare function parseErrorObject(value: unknown): ErrorObject;
export declare function parseDisposition(value: unknown): Disposition;
export declare function parseJsonRpcRequest(value: unknown): JsonRpcRequest;
export declare function parseJsonRpcNotification(value: unknown): JsonRpcNotification;
export declare function parseJsonRpcSuccessResponse(value: unknown): JsonRpcSuccessResponse;
export declare function parseJsonRpcErrorResponse(value: unknown): JsonRpcErrorResponse;
export declare function parseContentPart(value: unknown): ContentPart;
export declare function parseJsonRpcEnvelope(value: unknown): JsonRpcEnvelope;
export declare function runtimeSupportsApiVersion(version: string): boolean;
export declare function bundleSupportsApiVersion(version: string): boolean;
export declare function validateOffer(value: ContractOffer): void;
export declare function validateSelection(value: ContractSelection): void;
export declare function hostOffer(maxFrameBytes: number, maxConcurrentRequests: number): ContractOffer;
export declare function selectRequired(value: ContractOffer): ContractSelection;
export declare function negotiate(offer: ContractOffer, selection: ContractSelection): NegotiatedContract;
export declare function methodIsAvailable(contract: NegotiatedContract, name: string, direction: 'host_to_extension' | 'extension_to_host'): boolean;
export declare function requireMethod(contract: NegotiatedContract, name: string, direction: 'host_to_extension' | 'extension_to_host'): void;
export declare function validateDisposition(value: Disposition): void;
export declare function validateInitializeRequest(value: InitializeRequest): void;
export declare function validateInitializeResponse(value: InitializeResponse): void;
export declare function validateToolCallParams(value: ToolCallParams): void;
export declare function validateToolCallResult(value: ToolCallResult): void;
export declare function validateCancelRequestParams(value: CancelRequestParams): void;
export declare function validateShutdownParams(value: ShutdownParams): void;
export declare function validateShutdownResult(value: ShutdownResult): void;
export declare function validateErrorObject(value: ErrorObject): void;
export declare function canonicalJson(value: JsonValue): string;
export declare function canonicalFrame(value: JsonValue, maxFrameBytes: number): Uint8Array;
export declare function errorObject(name: keyof typeof ERROR_SPECS, data?: Presence<JsonValue>): ErrorObject;
