//! Checked-in static model definitions selected by provider declarations.

use ygg_ai::{OpenAiChatReasoningMode, Protocol, ReasoningEffort};

use super::contract::StaticModelSet;

/// Request encoding for a static model's OpenAI Chat reasoning capability.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(crate) enum StaticOpenAiChatReasoningProfile {
    /// Standard OpenAI-compatible `reasoning_effort` encoding.
    #[default]
    Standard,
    /// DeepSeek's explicit thinking toggle/replay encoding.
    DeepSeekThinking,
}

impl StaticOpenAiChatReasoningProfile {
    pub(crate) fn openai_chat_mode(self) -> OpenAiChatReasoningMode {
        match self {
            Self::Standard => OpenAiChatReasoningMode::Standard,
            Self::DeepSeekThinking => OpenAiChatReasoningMode::DeepSeekThinking,
        }
    }
}

/// Static model metadata used by multi-protocol providers.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StaticModelPreset {
    pub id: &'static str,
    pub name: &'static str,
    pub protocol: Protocol,
    pub context_window: u64,
    pub max_output_tokens: u64,
    pub vision: bool,
    pub reasoning: bool,
    pub max_reasoning_effort: ReasoningEffort,
    /// Request encoding used for this static model's OpenAI Chat reasoning.
    pub openai_chat_reasoning_profile: StaticOpenAiChatReasoningProfile,
}

impl StaticModelPreset {
    #[allow(clippy::too_many_arguments)]
    const fn new(
        id: &'static str,
        name: &'static str,
        protocol: Protocol,
        context_window: u64,
        max_output_tokens: u64,
        vision: bool,
        reasoning: bool,
        max_reasoning_effort: ReasoningEffort,
    ) -> Self {
        Self {
            id,
            name,
            protocol,
            context_window,
            max_output_tokens,
            vision,
            reasoning,
            max_reasoning_effort,
            openai_chat_reasoning_profile: StaticOpenAiChatReasoningProfile::Standard,
        }
    }

    const fn with_deepseek_thinking(mut self) -> Self {
        self.openai_chat_reasoning_profile = StaticOpenAiChatReasoningProfile::DeepSeekThinking;
        self
    }
}

pub const MINIMAX_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "MiniMax-M2.7",
        "MiniMax-M2.7",
        Protocol::AnthropicMessages,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "MiniMax-M2.7-highspeed",
        "MiniMax-M2.7-highspeed",
        Protocol::AnthropicMessages,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "MiniMax-M3",
        "MiniMax-M3",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
];

// Ported from @earendil-works/pi-ai 0.80.10. Models using Google's protocol
// are intentionally omitted until Ygg implements google-generative-ai.
pub const OPENCODE_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "big-pickle",
        "Big Pickle",
        Protocol::OpenAiChat,
        200_000,
        32_000,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-fable-5",
        "Claude Fable 5",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-haiku-4-5",
        "Claude Haiku 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-opus-4-1",
        "Claude Opus 4.1",
        Protocol::AnthropicMessages,
        200_000,
        32_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-opus-4-5",
        "Claude Opus 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-opus-4-6",
        "Claude Opus 4.6",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-opus-4-7",
        "Claude Opus 4.7",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-opus-4-8",
        "Claude Opus 4.8",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-sonnet-4",
        "Claude Sonnet 4",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-sonnet-4-5",
        "Claude Sonnet 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-sonnet-4-6",
        "Claude Sonnet 4.6",
        Protocol::AnthropicMessages,
        1_000_000,
        64_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-sonnet-5",
        "Claude Sonnet 5",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "deepseek-v4-flash",
        "DeepSeek V4 Flash",
        Protocol::OpenAiChat,
        1_000_000,
        384_000,
        false,
        true,
        ReasoningEffort::Max,
    )
    .with_deepseek_thinking(),
    StaticModelPreset::new(
        "deepseek-v4-flash-free",
        "DeepSeek V4 Flash Free",
        Protocol::OpenAiChat,
        200_000,
        128_000,
        false,
        true,
        ReasoningEffort::Max,
    )
    .with_deepseek_thinking(),
    StaticModelPreset::new(
        "deepseek-v4-pro",
        "DeepSeek V4 Pro",
        Protocol::OpenAiChat,
        1_000_000,
        384_000,
        false,
        true,
        ReasoningEffort::Max,
    )
    .with_deepseek_thinking(),
    StaticModelPreset::new(
        "glm-5",
        "GLM-5",
        Protocol::OpenAiChat,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "glm-5.1",
        "GLM-5.1",
        Protocol::OpenAiChat,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "glm-5.2",
        "GLM-5.2",
        Protocol::OpenAiChat,
        1_000_000,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5",
        "GPT-5",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5-codex",
        "GPT-5 Codex",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5-nano",
        "GPT-5 Nano",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.1",
        "GPT-5.1",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.1-codex",
        "GPT-5.1 Codex",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.1-codex-max",
        "GPT-5.1 Codex Max",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.1-codex-mini",
        "GPT-5.1 Codex Mini",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.2",
        "GPT-5.2",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.2-codex",
        "GPT-5.2 Codex",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.3-codex",
        "GPT-5.3 Codex",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.4",
        "GPT-5.4",
        Protocol::OpenAiResponses,
        272_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.4-mini",
        "GPT-5.4 Mini",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.4-nano",
        "GPT-5.4 Nano",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.4-pro",
        "GPT-5.4 Pro",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.5",
        "GPT-5.5",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.5-pro",
        "GPT-5.5 Pro",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.6-luna",
        "GPT-5.6 Luna",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "gpt-5.6-sol",
        "GPT-5.6 Sol",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "gpt-5.6-terra",
        "GPT-5.6 Terra",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "grok-4.5",
        "Grok 4.5",
        Protocol::OpenAiChat,
        500_000,
        500_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "grok-build-0.1",
        "Grok Build 0.1",
        Protocol::OpenAiChat,
        256_000,
        256_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "hy3-free",
        "Hy3 Free",
        Protocol::OpenAiChat,
        190_000,
        64_000,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "kimi-k2.5",
        "Kimi K2.5",
        Protocol::OpenAiChat,
        262_144,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "kimi-k2.6",
        "Kimi K2.6",
        Protocol::OpenAiChat,
        262_144,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "kimi-k2.7-code",
        "Kimi K2.7 Code",
        Protocol::OpenAiChat,
        262_144,
        262_144,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "mimo-v2.5-free",
        "MiMo V2.5 Free",
        Protocol::OpenAiChat,
        200_000,
        32_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "minimax-m2.5",
        "MiniMax-M2.5",
        Protocol::OpenAiChat,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "minimax-m2.7",
        "MiniMax-M2.7",
        Protocol::OpenAiChat,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "minimax-m3",
        "MiniMax-M3",
        Protocol::OpenAiChat,
        512_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "nemotron-3-ultra-free",
        "Nemotron 3 Ultra Free",
        Protocol::OpenAiChat,
        1_000_000,
        128_000,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "north-mini-code-free",
        "North Mini Code Free",
        Protocol::OpenAiChat,
        256_000,
        64_000,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "qwen3.5-plus",
        "Qwen3.5 Plus",
        Protocol::AnthropicMessages,
        262_144,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "qwen3.6-plus",
        "Qwen3.6 Plus",
        Protocol::AnthropicMessages,
        262_144,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
];

/// Return static models for a declaration-selected set without branching on a
/// provider identifier.
pub(crate) fn static_models(set: StaticModelSet) -> &'static [StaticModelPreset] {
    match set {
        StaticModelSet::None => &[],
        StaticModelSet::MiniMax => MINIMAX_MODELS,
        StaticModelSet::OpenCode => OPENCODE_MODELS,
    }
}
