//! Checked-in static model definitions selected by provider declarations.

use ygg_ai::{OpenAiChatReasoningMode, Protocol, ReasoningEffort};

use super::contract::StaticModelSet;

/// Request encoding for a static model's OpenAI Chat reasoning capability.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub(crate) enum StaticOpenAiChatReasoningProfile {
    /// Standard OpenAI-compatible `reasoning_effort` encoding.
    #[default]
    Standard,
    /// DeepSeek's explicit thinking toggle/replay encoding.
    DeepSeekThinking,
}

impl StaticOpenAiChatReasoningProfile {
    pub(crate) fn openai_chat_mode(self) -> OpenAiChatReasoningMode {
        match self {
            Self::Standard => OpenAiChatReasoningMode::Standard,
            Self::DeepSeekThinking => OpenAiChatReasoningMode::DeepSeekThinking,
        }
    }
}

/// Static model metadata used by multi-protocol providers.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct StaticModelPreset {
    pub id: &'static str,
    pub name: &'static str,
    pub protocol: Protocol,
    pub context_window: u64,
    pub max_output_tokens: u64,
    pub vision: bool,
    pub reasoning: bool,
    pub max_reasoning_effort: ReasoningEffort,
    /// Request encoding used for this static model's OpenAI Chat reasoning.
    pub openai_chat_reasoning_profile: StaticOpenAiChatReasoningProfile,
}

impl StaticModelPreset {
    #[allow(clippy::too_many_arguments)]
    const fn new(
        id: &'static str,
        name: &'static str,
        protocol: Protocol,
        context_window: u64,
        max_output_tokens: u64,
        vision: bool,
        reasoning: bool,
        max_reasoning_effort: ReasoningEffort,
    ) -> Self {
        Self {
            id,
            name,
            protocol,
            context_window,
            max_output_tokens,
            vision,
            reasoning,
            max_reasoning_effort,
            openai_chat_reasoning_profile: StaticOpenAiChatReasoningProfile::Standard,
        }
    }

    const fn with_deepseek_thinking(mut self) -> Self {
        self.openai_chat_reasoning_profile = StaticOpenAiChatReasoningProfile::DeepSeekThinking;
        self
    }
}

pub const MINIMAX_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "MiniMax-M2.7",
        "MiniMax-M2.7",
        Protocol::AnthropicMessages,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "MiniMax-M2.7-highspeed",
        "MiniMax-M2.7-highspeed",
        Protocol::AnthropicMessages,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "MiniMax-M3",
        "MiniMax-M3",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
];

// Google models available from both Gemini Developer API and Vertex AI. Their
// native protocol preserves function-call and thought-signature state.
pub const GOOGLE_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "gemini-2.5-flash",
        "Gemini 2.5 Flash",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-2.5-flash-lite",
        "Gemini 2.5 Flash-Lite",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-2.5-pro",
        "Gemini 2.5 Pro",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-3-flash-preview",
        "Gemini 3 Flash Preview",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-3.1-flash-lite",
        "Gemini 3.1 Flash Lite",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-3.1-pro-preview",
        "Gemini 3.1 Pro Preview",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-3.1-pro-preview-customtools",
        "Gemini 3.1 Pro Preview Custom Tools",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-3.5-flash",
        "Gemini 3.5 Flash",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-flash-latest",
        "Gemini Flash Latest",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-flash-lite-latest",
        "Gemini Flash-Lite Latest",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
];

// Ported from @earendil-works/pi-ai 0.80.10.
pub const OPENCODE_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "big-pickle",
        "Big Pickle",
        Protocol::OpenAiChat,
        200_000,
        32_000,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-fable-5",
        "Claude Fable 5",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-haiku-4-5",
        "Claude Haiku 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-opus-4-1",
        "Claude Opus 4.1",
        Protocol::AnthropicMessages,
        200_000,
        32_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-opus-4-5",
        "Claude Opus 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-opus-4-6",
        "Claude Opus 4.6",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-opus-4-7",
        "Claude Opus 4.7",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-opus-4-8",
        "Claude Opus 4.8",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-sonnet-4",
        "Claude Sonnet 4",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-sonnet-4-5",
        "Claude Sonnet 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-sonnet-4-6",
        "Claude Sonnet 4.6",
        Protocol::AnthropicMessages,
        1_000_000,
        64_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "claude-sonnet-5",
        "Claude Sonnet 5",
        Protocol::AnthropicMessages,
        1_000_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "deepseek-v4-flash",
        "DeepSeek V4 Flash",
        Protocol::OpenAiChat,
        1_000_000,
        384_000,
        false,
        true,
        ReasoningEffort::Max,
    )
    .with_deepseek_thinking(),
    StaticModelPreset::new(
        "deepseek-v4-flash-free",
        "DeepSeek V4 Flash Free",
        Protocol::OpenAiChat,
        200_000,
        128_000,
        false,
        true,
        ReasoningEffort::Max,
    )
    .with_deepseek_thinking(),
    StaticModelPreset::new(
        "deepseek-v4-pro",
        "DeepSeek V4 Pro",
        Protocol::OpenAiChat,
        1_000_000,
        384_000,
        false,
        true,
        ReasoningEffort::Max,
    )
    .with_deepseek_thinking(),
    StaticModelPreset::new(
        "gemini-3-flash",
        "Gemini 3 Flash",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-3.1-pro",
        "Gemini 3.1 Pro Preview",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gemini-3.5-flash",
        "Gemini 3.5 Flash",
        Protocol::GoogleGenerativeAi,
        1_048_576,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "glm-5",
        "GLM-5",
        Protocol::OpenAiChat,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "glm-5.1",
        "GLM-5.1",
        Protocol::OpenAiChat,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "glm-5.2",
        "GLM-5.2",
        Protocol::OpenAiChat,
        1_000_000,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5",
        "GPT-5",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5-codex",
        "GPT-5 Codex",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5-nano",
        "GPT-5 Nano",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.1",
        "GPT-5.1",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.1-codex",
        "GPT-5.1 Codex",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.1-codex-max",
        "GPT-5.1 Codex Max",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.1-codex-mini",
        "GPT-5.1 Codex Mini",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.2",
        "GPT-5.2",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.2-codex",
        "GPT-5.2 Codex",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.3-codex",
        "GPT-5.3 Codex",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.4",
        "GPT-5.4",
        Protocol::OpenAiResponses,
        272_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.4-mini",
        "GPT-5.4 Mini",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.4-nano",
        "GPT-5.4 Nano",
        Protocol::OpenAiResponses,
        400_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.4-pro",
        "GPT-5.4 Pro",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.5",
        "GPT-5.5",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.5-pro",
        "GPT-5.5 Pro",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "gpt-5.6-luna",
        "GPT-5.6 Luna",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "gpt-5.6-sol",
        "GPT-5.6 Sol",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "gpt-5.6-terra",
        "GPT-5.6 Terra",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Max,
    ),
    StaticModelPreset::new(
        "grok-4.5",
        "Grok 4.5",
        Protocol::OpenAiChat,
        500_000,
        500_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "grok-build-0.1",
        "Grok Build 0.1",
        Protocol::OpenAiChat,
        256_000,
        256_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "hy3-free",
        "Hy3 Free",
        Protocol::OpenAiChat,
        190_000,
        64_000,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "kimi-k2.5",
        "Kimi K2.5",
        Protocol::OpenAiChat,
        262_144,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "kimi-k2.6",
        "Kimi K2.6",
        Protocol::OpenAiChat,
        262_144,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "kimi-k2.7-code",
        "Kimi K2.7 Code",
        Protocol::OpenAiChat,
        262_144,
        262_144,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "mimo-v2.5-free",
        "MiMo V2.5 Free",
        Protocol::OpenAiChat,
        200_000,
        32_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "minimax-m2.5",
        "MiniMax-M2.5",
        Protocol::OpenAiChat,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "minimax-m2.7",
        "MiniMax-M2.7",
        Protocol::OpenAiChat,
        204_800,
        131_072,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "minimax-m3",
        "MiniMax-M3",
        Protocol::OpenAiChat,
        512_000,
        128_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "nemotron-3-ultra-free",
        "Nemotron 3 Ultra Free",
        Protocol::OpenAiChat,
        1_000_000,
        128_000,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "north-mini-code-free",
        "North Mini Code Free",
        Protocol::OpenAiChat,
        256_000,
        64_000,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "qwen3.5-plus",
        "Qwen3.5 Plus",
        Protocol::AnthropicMessages,
        262_144,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "qwen3.6-plus",
        "Qwen3.6 Plus",
        Protocol::AnthropicMessages,
        262_144,
        65_536,
        true,
        true,
        ReasoningEffort::High,
    ),
];

pub const BEDROCK_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "anthropic.claude-3-5-sonnet-20240620-v1:0",
        "Claude 3.5 Sonnet (Bedrock)",
        Protocol::BedrockConverse,
        200_000,
        8_192,
        true,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "anthropic.claude-3-7-sonnet-20250219-v1:0",
        "Claude 3.7 Sonnet (Bedrock)",
        Protocol::BedrockConverse,
        200_000,
        8_192,
        true,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "anthropic.claude-sonnet-4-20250514-v1:0",
        "Claude Sonnet 4 (Bedrock)",
        Protocol::BedrockConverse,
        200_000,
        64_000,
        true,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "amazon.nova-pro-v1:0",
        "Amazon Nova Pro (Bedrock)",
        Protocol::BedrockConverse,
        300_000,
        5_000,
        true,
        false,
        ReasoningEffort::High,
    ),
];

/// Checked-in Mistral Chat Completions models. These retain the Mistral
/// transport profile while using the canonical OpenAI Chat model contract.
pub const MISTRAL_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "codestral-latest",
        "Codestral",
        Protocol::OpenAiChat,
        256_000,
        4_096,
        false,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "devstral-latest",
        "Devstral 2",
        Protocol::OpenAiChat,
        262_144,
        262_144,
        false,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "magistral-medium-latest",
        "Magistral Medium",
        Protocol::OpenAiChat,
        128_000,
        16_384,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "mistral-large-latest",
        "Mistral Large",
        Protocol::OpenAiChat,
        262_144,
        262_144,
        true,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "mistral-small-latest",
        "Mistral Small",
        Protocol::OpenAiChat,
        256_000,
        256_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "pixtral-large-latest",
        "Pixtral Large",
        Protocol::OpenAiChat,
        128_000,
        128_000,
        true,
        false,
        ReasoningEffort::High,
    ),
];

/// A conservative Workers AI inventory for its documented OpenAI-compatible
/// endpoint. Cloudflare can add models independently; these are the checked-in
/// models with complete capability and pricing metadata.
pub const CLOUDFLARE_WORKERS_AI_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "@cf/meta/llama-4-scout-17b-16e-instruct",
        "Llama 4 Scout 17B 16E Instruct",
        Protocol::OpenAiChat,
        131_000,
        16_384,
        true,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "@cf/mistralai/mistral-small-3.1-24b-instruct",
        "Mistral Small 3.1 24B Instruct",
        Protocol::OpenAiChat,
        128_000,
        128_000,
        false,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "@cf/moonshotai/kimi-k2.7-code",
        "Kimi K2.7 Code",
        Protocol::OpenAiChat,
        262_144,
        262_144,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "@cf/openai/gpt-oss-120b",
        "GPT OSS 120B",
        Protocol::OpenAiChat,
        128_000,
        16_384,
        false,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "@cf/zai-org/glm-5.2",
        "GLM-5.2",
        Protocol::OpenAiChat,
        262_144,
        262_144,
        false,
        true,
        ReasoningEffort::High,
    ),
];

/// Common Cloudflare AI Gateway passthrough models. Gateway route selection is
/// declaration-owned: Claude uses Anthropic Messages, OpenAI reasoning models
/// use Responses, and Workers AI models use the compatibility route.
pub const CLOUDFLARE_AI_GATEWAY_MODELS: &[StaticModelPreset] = &[
    StaticModelPreset::new(
        "claude-haiku-4-5",
        "Claude Haiku 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-sonnet-4-5",
        "Claude Sonnet 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "claude-opus-4-5",
        "Claude Opus 4.5",
        Protocol::AnthropicMessages,
        200_000,
        64_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-4o",
        "GPT-4o",
        Protocol::OpenAiResponses,
        128_000,
        16_384,
        true,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-4o-mini",
        "GPT-4o mini",
        Protocol::OpenAiResponses,
        128_000,
        16_384,
        true,
        false,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "gpt-5.4",
        "GPT-5.4",
        Protocol::OpenAiResponses,
        1_050_000,
        128_000,
        true,
        true,
        ReasoningEffort::Xhigh,
    ),
    StaticModelPreset::new(
        "o3",
        "o3",
        Protocol::OpenAiResponses,
        200_000,
        100_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "o4-mini",
        "o4-mini",
        Protocol::OpenAiResponses,
        200_000,
        100_000,
        true,
        true,
        ReasoningEffort::High,
    ),
    StaticModelPreset::new(
        "workers-ai/@cf/moonshotai/kimi-k2.6",
        "Workers AI Kimi K2.6",
        Protocol::OpenAiChat,
        256_000,
        256_000,
        true,
        true,
        ReasoningEffort::High,
    ),
];

/// Return static models for a declaration-selected set without branching on a
/// provider identifier.
pub(crate) fn static_models(set: StaticModelSet) -> &'static [StaticModelPreset] {
    match set {
        StaticModelSet::None => &[],
        StaticModelSet::MiniMax => MINIMAX_MODELS,
        StaticModelSet::OpenCode => OPENCODE_MODELS,
        StaticModelSet::Bedrock => BEDROCK_MODELS,
        StaticModelSet::Mistral => MISTRAL_MODELS,
        StaticModelSet::CloudflareWorkersAi => CLOUDFLARE_WORKERS_AI_MODELS,
        StaticModelSet::CloudflareAiGateway => CLOUDFLARE_AI_GATEWAY_MODELS,
        StaticModelSet::Google => GOOGLE_MODELS,
    }
}
