//! Goal-aware continuation state for session actors.
//!
//! The driver deliberately depends on a small store trait rather than on a
//! concrete frontend or persistence crate. The graphical `ygg-serve` goal
//! store can therefore be adapted without making the core agent depend on the
//! optional extension.

use std::sync::{Arc, Mutex};
use std::time::Duration;

use thiserror::Error;

/// Grace period between a settled turn and an automatic goal continuation.
pub const DEFAULT_GOAL_GRACE_PERIOD: Duration = Duration::from_secs(2);

/// Prompt template used for automatic goal continuations.
///
/// The `{objective}` placeholder is replaced by [`continuation_prompt`].
pub const GOAL_CONTINUATION_PROMPT_TEMPLATE: &str = "Continue working toward the goal: {objective}.\nCheck progress against concrete evidence (files, command output, tests) before deciding.\nIf the goal is fully achieved, end your reply with GOAL_COMPLETE.\nIf you cannot make further progress, end your reply with GOAL_BLOCKED and the reason.";

/// Lifecycle state shared by goal stores and the continuation driver.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[non_exhaustive]
pub enum GoalStatus {
    /// The driver may continue working toward the objective.
    Active,
    /// The objective remains stored but continuation is suspended.
    Paused,
    /// The objective was reached.
    Complete,
    /// The driver could not make further progress.
    Blocked,
    /// The configured continuation budget was exhausted.
    BudgetLimited,
}

/// The bounded goal data required by the continuation driver.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GoalState {
    /// The objective the driver should pursue.
    pub objective: String,
    /// Current lifecycle state.
    pub status: GoalStatus,
    /// Maximum continuation turns, or unlimited when absent.
    pub turn_budget: Option<u32>,
    /// Number of continuation turns already consumed.
    pub turns_used: u32,
    /// Store-provided creation timestamp retained for round-tripping.
    pub created_at: String,
}

/// Identifies who supplied the prompt whose response just settled.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GoalTurnSource {
    /// A prompt or control message supplied by the user.
    User,
    /// A prompt generated by this driver.
    Continuation,
}

/// A terminal marker found at the end of an assistant response.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum GoalMarker {
    /// The objective was reported as complete.
    Complete,
    /// The objective was reported as blocked.
    Blocked,
}

/// Decision returned after a turn settles.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GoalDecision {
    /// There is no goal or the goal is not active.
    Inactive,
    /// The driver should wait, then call [`GoalDriver::fire_continuation`].
    Wait {
        /// Grace period before the continuation is eligible.
        delay: Duration,
        /// Objective included in the eventual prompt.
        objective: String,
    },
    /// A no-tool continuation was observed; user input is required to resume.
    Suppressed,
    /// The response marked the goal complete.
    Complete,
    /// The response marked the goal blocked.
    Blocked,
    /// The goal's continuation budget is exhausted.
    BudgetLimited,
    /// The goal is paused, including after a session error.
    Paused,
}

/// One continuation prompt accepted for execution.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GoalContinuation {
    /// Prompt text to append to the session and submit to the model.
    pub prompt: String,
    /// Goal state after reserving this continuation turn.
    pub goal: GoalState,
}

/// Persistence operations needed by [`GoalDriver`].
///
/// Implementations should use the same durable state as the frontend goal
/// command. Errors are strings here so the core crate stays independent of
/// the extension's error type; adapters should return sanitized diagnostics.
pub trait GoalStore: Send + Sync {
    /// Reads the current goal for a session.
    fn get(&self, session_id: &str) -> Result<Option<GoalState>, String>;

    /// Reserves one continuation turn and enforces the configured budget.
    fn record_turn(&self, session_id: &str) -> Result<GoalState, String>;

    /// Marks a goal complete.
    fn mark_complete(&self, session_id: &str) -> Result<GoalState, String>;

    /// Marks a goal blocked.
    fn mark_blocked(&self, session_id: &str) -> Result<GoalState, String>;

    /// Pauses a goal after a session error.
    fn pause(&self, session_id: &str) -> Result<GoalState, String>;
}

/// Errors returned by goal-store operations.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum GoalDriverError {
    /// The configured store rejected or could not complete an operation.
    #[error("goal store error: {0}")]
    Store(String),
}

#[derive(Debug)]
enum DriverState {
    Idle,
    Waiting,
    Running,
    Suppressed,
}

/// Coordinates goal state transitions around settled agent turns.
///
/// The driver is cloneable so an [`Agent`](crate::Agent) can keep the shared
/// state while its caller-driven run stream owns a lightweight handle. All
/// store operations remain synchronous and bounded, matching the existing
/// goal-store API.
#[derive(Clone)]
pub struct GoalDriver {
    store: Arc<dyn GoalStore>,
    session_id: String,
    grace_period: Duration,
    state: Arc<Mutex<DriverState>>,
}

impl GoalDriver {
    /// Creates a driver using the production two-second grace period.
    pub fn new(store: Arc<dyn GoalStore>, session_id: impl Into<String>) -> Self {
        Self {
            store,
            session_id: session_id.into(),
            grace_period: DEFAULT_GOAL_GRACE_PERIOD,
            state: Arc::new(Mutex::new(DriverState::Idle)),
        }
    }

    /// Overrides the grace period, primarily for deterministic tests.
    pub fn with_grace_period(mut self, grace_period: Duration) -> Self {
        self.grace_period = grace_period;
        self
    }

    /// Returns the session key used for store operations.
    pub fn session_id(&self) -> &str {
        &self.session_id
    }

    /// Clears anti-spin suppression when the user speaks.
    pub fn user_spoke(&self) {
        if let Ok(mut state) = self.state.lock() {
            *state = DriverState::Idle;
        }
    }

    /// Processes a successfully settled assistant response.
    ///
    /// `made_tool_call` describes the whole prompt run, not just the final
    /// no-tool assistant turn. This lets a continuation that made useful tool
    /// progress schedule another continuation after its final answer.
    pub fn turn_settled(
        &self,
        source: GoalTurnSource,
        response: &str,
        made_tool_call: bool,
    ) -> Result<GoalDecision, GoalDriverError> {
        let Some(goal) = self
            .store
            .get(&self.session_id)
            .map_err(GoalDriverError::Store)?
        else {
            self.set_state(DriverState::Idle);
            return Ok(GoalDecision::Inactive);
        };

        if goal.status != GoalStatus::Active {
            self.set_state(match goal.status {
                GoalStatus::Paused => DriverState::Idle,
                GoalStatus::Complete | GoalStatus::Blocked | GoalStatus::BudgetLimited => {
                    DriverState::Idle
                }
                GoalStatus::Active => DriverState::Idle,
            });
            return Ok(match goal.status {
                GoalStatus::Paused => GoalDecision::Paused,
                GoalStatus::Complete => GoalDecision::Complete,
                GoalStatus::Blocked => GoalDecision::Blocked,
                GoalStatus::BudgetLimited => GoalDecision::BudgetLimited,
                GoalStatus::Active => GoalDecision::Inactive,
            });
        }

        match detect_goal_marker(response) {
            Some(GoalMarker::Complete) => {
                self.store
                    .mark_complete(&self.session_id)
                    .map_err(GoalDriverError::Store)?;
                self.set_state(DriverState::Idle);
                return Ok(GoalDecision::Complete);
            }
            Some(GoalMarker::Blocked) => {
                self.store
                    .mark_blocked(&self.session_id)
                    .map_err(GoalDriverError::Store)?;
                self.set_state(DriverState::Idle);
                return Ok(GoalDecision::Blocked);
            }
            None => {}
        }

        if source == GoalTurnSource::Continuation && !made_tool_call {
            self.set_state(DriverState::Suppressed);
            return Ok(GoalDecision::Suppressed);
        }

        self.set_state(DriverState::Waiting);
        Ok(GoalDecision::Wait {
            delay: self.grace_period,
            objective: goal.objective,
        })
    }

    /// Fires a continuation after the grace period has elapsed.
    ///
    /// The current goal is re-read before reserving the turn, so a concurrent
    /// pause, clear, completion, or budget update wins over a stale wait.
    pub fn fire_continuation(&self) -> Result<Option<GoalContinuation>, GoalDriverError> {
        if !self.is_waiting() {
            return Ok(None);
        }
        let Some(goal) = self
            .store
            .get(&self.session_id)
            .map_err(GoalDriverError::Store)?
        else {
            self.set_state(DriverState::Idle);
            return Ok(None);
        };
        if goal.status != GoalStatus::Active {
            self.set_state(DriverState::Idle);
            return Ok(None);
        }

        let goal = self
            .store
            .record_turn(&self.session_id)
            .map_err(GoalDriverError::Store)?;
        if !matches!(goal.status, GoalStatus::Active | GoalStatus::BudgetLimited) {
            self.set_state(DriverState::Idle);
            return Ok(None);
        }
        self.set_state(DriverState::Running);
        Ok(Some(GoalContinuation {
            prompt: continuation_prompt(&goal.objective),
            goal,
        }))
    }

    /// Pauses an active goal after an unrecoverable session error.
    pub fn session_error(&self) -> Result<(), GoalDriverError> {
        let Some(goal) = self
            .store
            .get(&self.session_id)
            .map_err(GoalDriverError::Store)?
        else {
            self.set_state(DriverState::Idle);
            return Ok(());
        };
        if goal.status == GoalStatus::Active {
            self.store
                .pause(&self.session_id)
                .map_err(GoalDriverError::Store)?;
        }
        self.set_state(DriverState::Idle);
        Ok(())
    }

    fn is_waiting(&self) -> bool {
        self.state
            .lock()
            .map(|state| matches!(*state, DriverState::Waiting))
            .unwrap_or(false)
    }

    fn set_state(&self, next: DriverState) {
        if let Ok(mut state) = self.state.lock() {
            *state = next;
        }
    }
}

/// Builds the exact prompt submitted for one automatic continuation.
pub fn continuation_prompt(objective: &str) -> String {
    format!(
        "Continue working toward the goal: {objective}.\nCheck progress against concrete evidence (files, command output, tests) before deciding.\nIf the goal is fully achieved, end your reply with GOAL_COMPLETE.\nIf you cannot make further progress, end your reply with GOAL_BLOCKED and the reason."
    )
}

/// Finds a completion marker when it is the final non-whitespace token.
pub fn detect_goal_marker(response: &str) -> Option<GoalMarker> {
    let last_line = response
        .lines()
        .rev()
        .find(|line| !line.trim().is_empty())?
        .trim();
    if last_line == "GOAL_COMPLETE" {
        Some(GoalMarker::Complete)
    } else if last_line == "GOAL_BLOCKED" || last_line.starts_with("GOAL_BLOCKED ") {
        Some(GoalMarker::Blocked)
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU32, Ordering};

    #[derive(Clone)]
    struct MemoryStore {
        state: Arc<Mutex<Option<GoalState>>>,
        records: Arc<AtomicU32>,
    }

    impl MemoryStore {
        fn active(budget: Option<u32>) -> Self {
            Self {
                state: Arc::new(Mutex::new(Some(GoalState {
                    objective: "finish the tests".into(),
                    status: GoalStatus::Active,
                    turn_budget: budget,
                    turns_used: 0,
                    created_at: "now".into(),
                }))),
                records: Arc::new(AtomicU32::new(0)),
            }
        }

        fn state(&self) -> GoalState {
            self.state.lock().unwrap().clone().unwrap()
        }
    }

    impl GoalStore for MemoryStore {
        fn get(&self, _session_id: &str) -> Result<Option<GoalState>, String> {
            Ok(self.state.lock().unwrap().clone())
        }

        fn record_turn(&self, _session_id: &str) -> Result<GoalState, String> {
            self.records.fetch_add(1, Ordering::Relaxed);
            let mut state = self.state.lock().unwrap();
            let state = state.as_mut().unwrap();
            state.turns_used += 1;
            if state
                .turn_budget
                .is_some_and(|budget| state.turns_used >= budget)
            {
                state.status = GoalStatus::BudgetLimited;
            }
            Ok(state.clone())
        }

        fn mark_complete(&self, _session_id: &str) -> Result<GoalState, String> {
            let mut state = self.state.lock().unwrap();
            let state = state.as_mut().unwrap();
            state.status = GoalStatus::Complete;
            Ok(state.clone())
        }

        fn mark_blocked(&self, _session_id: &str) -> Result<GoalState, String> {
            let mut state = self.state.lock().unwrap();
            let state = state.as_mut().unwrap();
            state.status = GoalStatus::Blocked;
            Ok(state.clone())
        }

        fn pause(&self, _session_id: &str) -> Result<GoalState, String> {
            let mut state = self.state.lock().unwrap();
            let state = state.as_mut().unwrap();
            state.status = GoalStatus::Paused;
            Ok(state.clone())
        }
    }

    #[test]
    fn continuation_prompt_contains_the_objective_and_contract() {
        let prompt = continuation_prompt("finish the tests");
        assert!(prompt.contains("Continue working toward the goal: finish the tests."));
        assert!(prompt.contains("GOAL_COMPLETE"));
        assert!(prompt.contains("GOAL_BLOCKED"));
    }

    #[test]
    fn active_goal_waits_then_reserves_one_continuation() {
        let store = MemoryStore::active(None);
        let driver = GoalDriver::new(Arc::new(store.clone()), "session")
            .with_grace_period(Duration::from_millis(5));
        assert_eq!(
            driver.turn_settled(GoalTurnSource::User, "progress", false),
            Ok(GoalDecision::Wait {
                delay: Duration::from_millis(5),
                objective: "finish the tests".into(),
            })
        );
        let continuation = driver.fire_continuation().unwrap().unwrap();
        assert!(continuation.prompt.contains("finish the tests"));
        assert_eq!(store.records.load(Ordering::Relaxed), 1);
    }

    #[test]
    fn no_tool_continuation_is_suppressed_until_user_speaks() {
        let store = MemoryStore::active(None);
        let driver = GoalDriver::new(Arc::new(store.clone()), "session");
        driver
            .turn_settled(GoalTurnSource::User, "start", false)
            .unwrap();
        driver.fire_continuation().unwrap();
        assert_eq!(
            driver.turn_settled(GoalTurnSource::Continuation, "done", false),
            Ok(GoalDecision::Suppressed)
        );
        driver.user_spoke();
        assert!(matches!(
            driver.turn_settled(GoalTurnSource::User, "again", false),
            Ok(GoalDecision::Wait { .. })
        ));
    }

    #[test]
    fn markers_update_goal_state_before_continuation() {
        let complete_store = MemoryStore::active(None);
        let complete_driver = GoalDriver::new(Arc::new(complete_store.clone()), "session");
        assert_eq!(
            complete_driver
                .turn_settled(GoalTurnSource::User, "verified\nGOAL_COMPLETE", false)
                .unwrap(),
            GoalDecision::Complete
        );
        assert_eq!(complete_store.state().status, GoalStatus::Complete);

        let blocked_store = MemoryStore::active(None);
        let blocked_driver = GoalDriver::new(Arc::new(blocked_store.clone()), "session");
        assert_eq!(
            blocked_driver
                .turn_settled(GoalTurnSource::User, "GOAL_BLOCKED cannot proceed", false,)
                .unwrap(),
            GoalDecision::Blocked
        );
        assert_eq!(blocked_store.state().status, GoalStatus::Blocked);
    }

    #[test]
    fn budget_limited_goal_still_runs_the_last_reserved_turn() {
        let store = MemoryStore::active(Some(1));
        let driver = GoalDriver::new(Arc::new(store.clone()), "session");
        driver
            .turn_settled(GoalTurnSource::User, "start", false)
            .unwrap();
        assert!(driver.fire_continuation().unwrap().is_some());
        assert_eq!(store.state().status, GoalStatus::BudgetLimited);
        assert_eq!(
            driver
                .turn_settled(GoalTurnSource::Continuation, "no more", true)
                .unwrap(),
            GoalDecision::BudgetLimited
        );
    }

    #[test]
    fn session_error_pauses_active_goal() {
        let store = MemoryStore::active(None);
        let driver = GoalDriver::new(Arc::new(store.clone()), "session");
        driver.session_error().unwrap();
        assert_eq!(store.state().status, GoalStatus::Paused);
    }

    #[test]
    fn markers_are_only_recognized_at_the_end() {
        assert_eq!(detect_goal_marker("GOAL_COMPLETE\nmore"), None);
        assert_eq!(
            detect_goal_marker("done\nGOAL_COMPLETE"),
            Some(GoalMarker::Complete)
        );
        assert_eq!(
            detect_goal_marker("done\nGOAL_BLOCKED because"),
            Some(GoalMarker::Blocked)
        );
    }
}
